TITLE = compsc

EPS = selfemu.eps pack_state.eps arch.eps
EPS += perf_tp.eps perf_spec_req.eps perf_spec_250.eps perf_spec_resp.eps
EPS += timeline_compsc.eps timeline_pv.eps timeline_bond.eps

include ../scripts/tex.rules
