#+TITLE:  我们可以控制技术吗？进一步探讨技术发展于人类未来的关系
* 前言
  从小就听着“精通数理化，走遍全天下”这样的教导长大，很多中国学生是非
  常迷信科学的。人们所掌握的科学教会了人们从个别到一般、从一般到个别
  的归纳与演绎的思维方法；从抽象到具体的思维形式；以及逻辑的、综合的
  分析事物的发展变化规律。

  说到人类如何控制技术的话题，最先让我想到的就是电影《终结者》中高度
  智能化的机器人，如果一项技术发展到人类不能控制的程度，人类的未来也
  许不是受益于技术，而是被技术所终结。

  世界是物质的，物质是运动的，运动虽然多样性，但却有规律可循。人们希
  望通过这些规律和知识掌握未来，但事物的发展是不以人类意志为转移的。
  人类可以通过科学技术的手段从世间万物的普遍联系中探得一点奥秘，从事
  物的的发展中窥得一些规律，但却不能利用技术主宰未来，需要顺应规律开
  创人类的未来。

  本文将从人工智能和进化论两个方向来讲讲科学技术的发展与人类未来的关系。
* 人工智能
*** 人工智能的起源
	人工智能（Artificial Intelliengence）是计算机科学技术的一个重要分
	支。它没有一个官方的定义，只有一个直观的理解：机器可以像人一样进行
	思考和活动。人工智能理论的诞生，一般认为是在上个世纪五十年代中期，
	标志为达特茅斯夏季讨论会。在这个为期2个月的讨论会上，四位年轻学
	者：约翰•麦卡锡（John McCarthy）、马文•明斯基（Marvin Minsky）、纳
	撒尼尔•罗彻斯特（Nathaniel Rochester）和克劳德•香农（Claude
	Shannon）邀请了包括数学、神经心理学、精神病信息论等领域的10位学
	者，共同讨论使用机器模拟人类智能的方法和可行性。
*** 人们关于人工智能的猜想
	人工智能的出现，对公众的感受，主要是新奇和惊叹。人们惊讶于科学技术
    的发展，憧憬有朝一日机器可以帮助人们完成一切任务。而同时，人们又从
    人工智能上嗅到了威胁和敌意。

	1989年，一次人类棋手与计算机进行的国际象棋比赛中，出现了一次意外。
    计算机供电系统的漏电，导致人类棋手被高压电击中毙命。而在这一意外出
    现之前，计算机刚连输了人类棋手三局。这次意外引起了人们的无限遐想，
    乃至最后法官试图宣判事故中的计算机有罪：因为它恼羞成怒将对手电死了。
    当然最后的调查发现这只是一次普通的意外，不过人们已经认为，人工智能
    对人们可能造成伤害。

	1984年上映的经典大片《终结者》中，就描述了人们对这一可能性的遐想。
    剧中描述了在几十年后，计算机系统利用人工智能统治了整个地球，而试图
    将所有人类消灭。类似的大片还有很多，例如《黑客帝国》系列等。

	这些事情到底有没有可能发生呢？如果有可能，那可能是在多远的将来呢？
*** 当今的人工智能
	60年来，人工智能有着飞速而广阔的发展。对人工智能的研究主要可以分为
    两个类别：模仿人的思考行为，和理性的思考行为。第一种人工智能是将机
    器与人相比，使得机器尽可能地靠近人；而第二种人工智能是试图赋予机器
    正确与错误的观念，使得机器可以进行判断、推理、归纳和演绎。
**** 模仿人的思考行为
	 1950年，阿兰•图灵（Alan Turing）提出图灵测试，为智能提供了一个满足
     可操作要求的定义。测试是这样的：将一个正常人和一台机器放于一间房间
     中，而在另一间房间中放置另一个正常的人（询问者）。询问者无法看到第
     一个房间的情况，而只能通过一个文本终端同第一个房间联系，同时也无法
     得知与自己联系的是人还是机器。如果询问者通过该终端分别与人和机器交
     流后，不能区别出机器和人，则可以认为机器是具有智能的。

	 显然，这种定义是将人和机器进行无差别的比对，从而对人工智能做出定义。
     虽然在历史上有过很多使得人们惊奇的机器出现，但是至今仍然没有一台机
     器或者一个电脑程序，可以通过图灵测试。
**** 理性的思考行为
	 1985年，查尼艾克（E. Charniak）和麦克德莫特（D. McDemott）提出人工
     智能是用计算模型来研究智力的能力。一个系统如果能够在它所知的范围内
     正确行事，那它就是理性的。

	 而对于正确的定义，通常是指逻辑学上的正确。借助于19世纪后期和20世纪
     早期发展起来的形式逻辑，人工智能在推理和演绎方面有着巨大的进步。到
     1965年，原则上已经有程序可以求解任何用逻辑符号描述的可解问题。
*** 人工智能会成为脱缰野马吗？
	有一个很经典的哲学悖论：如果人的大脑简单到人可以研究清楚，那么人一
    定愚蠢到没法研究出这样的大脑。这句话可以用一句古诗来解释：不识庐山
    真面目，只缘身在此山中。使用人脑来分析人脑，是不可能分析清楚的，只
    有站在比人脑更高的层面上，才可能分析清楚人脑的所有细节。如果每个人
    都是用自己大脑进行思考的话，可以认为人工智能是永远无法跟上人类大脑
    的能力的。

	现今的人工智能，距离电影中所描述的还很远很远。机器甚至连听懂人说
    话，都是非常困难的一件事情。现在对人工智能的研究，也只是将机器放置
    在一个人类的辅助工具的位置上进行的。在这样的前提下，人工智能不会朝
    着与人类智能靠近的方向发展，而只会朝着与人类智能互补的方向发展。

	所以说，其实在电影中人们所担心的那一幕一幕，其实并不可能出现。人类
    根本不可能研究清楚人脑的能力，也就无法制造出和人脑一样强大甚至比人
    脑强大的机器。何况，人们做这方面研究时，还并不是朝着这个方向努力的。
* 进化论
** 进化论的起源
   1858年7月1日C.R.达尔文与A.R.华莱士在伦敦林奈学会上宣读了关于物种起源
   的论文。后人称他们的自然选择学说为达尔文·华莱士学说。其核心自然选择
   原理的大意如下：生物都有繁殖过剩的倾向，所以生物必须“为生存而斗争”。
   在同一种群中的个体存在着变异，那些具有能适应环境的有利变异的个体将存
   活下来，并繁殖后代，不具有有利变异的个体就被淘汰。如果自然条件的变化
   是有方向的，则在历史过程中，经过长期的自然选择，微小的变异就得到积累
   而成为显著的变异。
** 人类对于生物的驯化和养殖
   在人类出现之前，动物和植物完全是依照达尔文的进化论进行繁衍和变化的。
   物种的变异和淘汰，在不受干扰的状况下进行。这样，物种们在漫漫历史长河
   中，进化和灭绝。适合气候环境的物种繁衍下去，不适合气候环境的物种灭
   绝；强壮没有敌人的物种进化得更强，而天敌众多的动物悄然消失。

   人类出现之后，大量地将野生动物和植物驯服家养，并且修剪剔除后，选出"
   优秀"的物种一代一代繁衍下去。野生动植物不断地被人类所清理，而取而代
   之的则是一批一批温顺柔弱的类似物种。有皮薄肉厚没有籽的西瓜，也有巴掌
   大小可以装进杯子里的迷你小狗。

   在进化理论出现后，手工杂交/选择物种的技术层出不穷。有袁隆平的杂交水
   稻，很大地解决了粮食问题；有手工抗体培育，培养出可用于对付疾病的疫
   苗；有对鲤鱼的挑选繁殖，给人们带来美丽的金鱼；也有对野生动物的驯化，
   使以前只有图画中出现的动物成为人们的掌中玩具。

   进化理论和生物技术对人类的发展进步，作用是巨大的。但是在这些作用的背
   后，有没有一只看不见的魔手，向人们悄悄袭来呢？
*** 驯化的生物，温室的花朵
	人工培育的生物，的确对人类带来了很大的利益。但是人工培育生物，就相
    当于人类利用双手，去代替大自然挑选"适合"生存下来的物种。将这份需要
    全面考虑，而且残酷的工作，交给了人们自己来做。人们会像大自然一般全
    面考虑吗？会像大自然一般公平吗？答案是否定的。

	在世界上存在了千百年的植物，到了温室中，需要人们的双手才能打败杂
    草；动物园里的狮子，看到羊和看到游客没什么区别，完全没有捕食的欲望
    和能力；装进杯子里的迷你小狗，平均寿命竟不足一年。这些经过人们选
    择，符合人们期望的病态的生物，堂而皇之地存活了下来；而真正依靠自己
    能力捕食，可以对抗部分天灾的生物，却因为人祸而被世界所抛弃。

	世界上被人们完全掌控的地区，基本上都失去了让生物正常繁衍进化的平
    台；而生物们只能在"自然保护区"内，体验过去的美好时光。在不久的将
    来，人们必将发现，自己培育的物种，根本经不起自然的考验。一块小石头
    就可以压死的大树，一条小河就可以冻死的狮子。而这时，进化论已不再成
    立，剩余的物种已经没法继续健康地进化。
*** 有两全其美的解决办法吗？
	针对这些问题，人类也做出了相应的对策。对于自己培育的物种，都想方设
    法将其培育出在自然中生存的能力。比如人们培育出的抗虫、抗病毒的植物。
    做这些事情的动机，无独有偶全部都是为了物种更利于人们的利用。而真正
    能够解决这些问题的方法，则是人工地培育出适合环境、生命力顽强的物种。

	即使是这样，也还是存在一些严重的问题。自然选择的过程往往是漫长而残
    酷的，随着大批量的生物在漫漫历史长河中死去，真正适合环境的生物脱颖
    而出。而人工选择则是一个非常急功近利的过程。前苏联科学家在50多年前
    开始的一项实验，对狐狸的驯化工作，在进行了10代繁衍之后，便得到了温
    顺的狐狸。但是在这个过程中，样本是如此的少，根本没有办法对生命力、
    抗天灾能力、抗天敌能力等重要能力进行评测。繁衍出来的狐狸，根本没有
    办法和自然选择出来的狐狸品种共同存在。而人工选择则自然没有办法像自
    然选择一般使用如此大的样本。
** 人类本身的进化
   人类本身，也是根据进化论来繁衍进化的。而随着科学技术的发展，以及经济
   社会等因素的影响，人类的进化越来越偏离自然选择的轨道。
*** 社会选择
	市长家的瘦弱儿子，超生了3胎，而同时隔壁搬砖块的健康小伙，则连女朋友
    都找不到；没名气小学院里的聪明教授，没有经费研究，而孤老终生；对面
    教堂里只会念书本唱宗教歌的笨神父，则私底下和好几个修女有了孩子。这
    样的事情，每天都在这个世界上发生。获得繁衍的机会，不再是完全由体格
    /脑力决定，而往往是由社会地位和经济条件决定。
*** 人类社会的发展
	人类的社会也完全是由科学技术所左右的。有一个很经典的例子，是经济博
    弈论的。讲的是当运输成本和生产成本呈不同比例时，对社会的聚集性带来
    的影响。当运输成本较生产成本高的时候，人群会以小村落的形式出现，并
    且村落的位置是完全随机出现的。而当运输成本较生产成本低的时候，人群
    通常以大都会的形式出现。 所以古代人类社区通常是由小村落组成，而现在
    则往往是由少数几个人口密布的大城市。

	这是符合人类总利益的自然选择的结果，人口密布的大城市带来了飞速发展
    的经济。但是现在在世界上发生的事情，则未必有这样的好处。

	科学技术的发展让人们变懒了，肥胖症的比例越来越高。就像电影《Wall-E》
    中描述的那样，科学技术的进一步发展，会让世界上每一个人，变得慵懒而
    肥胖，离开屏幕便无法交流。科学技术的发展还让世界变得忙碌，人们也不
    再像过去一样可以下班后去邻居家串个门，住了多年的房子连邻居都不认识
    在现在则是很常见的事情。

	科学技术通常是在无意的情况下影响人类的社会性和群体性的，而这种影响
    未必是人们所希望看到的。在今后是否应该预先考虑这些影响而作出相应的
    决策，从而使得人类的社会性和群体性向合理健康的方向发展，则是人们需
    要考虑的下一个问题。
* 结语
  科学技术的飞速发展对人类带来了非常多的好处。而在今天看来，人们对于科
  学技术的控制显得游刃有余。人们可以控制技术吗？可以让技术完全地为人类
  服务吗？

  在人工智能的角度来看，人们似乎不用太担心类似终结者一样的机器出现，也
  不用担心人们最终会被装在Matrix由电脑来控制思维情感。而在进化论的角度
  来看，人类最好还是对生物科学保守一些，避免健康物种的灭绝；在人类社会
  这个角度来看，控制科学技术的发展以让人类健康地发展则是必要的。
* 参考文献
** 人工智能 史忠植 王文杰 国防工业出版社
** 智能计算——若干理论问题及其应用 梁久祯 国防工业出版社
** 网络虚拟环境——设计与实现 Sandeep Singhal, Michael Zyda 电子工业出版社
** 自然语言处理综论 Daniel Jurafsky, James H. Martin 电子工业出版社
** 自动规划：理论和实践 Malik Ghallab, Dana Nau, Paolo Traverso 清华大学出版社
** 遗传学 卢良峰 陆文静 中国农业出版社
** 遗传学 戴灼华 王亚馥 粟翼玟 高等教育出版社
** 进化论 百度百科 http://baike.baidu.com/view/28618.htm
